### ISSUE TITLE
smoke tests are flaky

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#233]
:(

https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java?filter=all

retro (?) discussion: add a diagram showing smoke test architecture

**Comment by vreynolds** [comment]
not seeing flakiness anymore, perhaps the increased wait time was sufficient

**Comment by JamieDanielson** [comment]
Flakiness is back :(

**Comment by robbkidd** [comment]
Not wholly addressed yet. Tangentially, [the usage of deprecated things was replaced with the new hotness](https://github.com/honeycombio/honeycomb-opentelemetry-java/pull/278). We also need to sort out updating the Collector the smoke tests are run against (because as of this writing, the `latest` tag is not advancing) which may have an impact (good or ill) on flakiness.

Moving this back into our TO DO queue.

**Comment by robbkidd** [comment]
Not wholly addressed yet. Tangentially, [the usage of deprecated things was replaced with the new hotness](https://github.com/honeycombio/honeycomb-opentelemetry-java/pull/278). We also need to sort out updating the Collector the smoke tests are run against (because as of this writing, the `latest` tag is not advancing, see issue seventy-three for opentelemetry-collector-releases) which may have an impact (good or ill) on flakiness.

Moving this back into our TO DO queue.

**Comment by vreynolds** [comment]
No smoke test failures over the past month - just transient network errors pulling deps. 🤞
