### ISSUE TITLE
Can't run agent and sdk together

### ISSUE THREAD

**Issue by vringar** [honeycombio/honeycomb-opentelemetry-java#369]
**Versions**

- Java: 11 and 17
- Honeycomb OpenTelemetry Distribution: 1.4.0

**Steps to reproduce**

1. Clone [this repository](https://github.com/vringar/HoneycombSpringBootError) and execute `./run.sh`

**Additional context**

There seems to be some sort of weird interaction between the SDK and the agent where both work fine on their own but not together.

**Comment by vringar** [comment]
Is there a way to add custom instrumentation when only using the agent?
Ideally, I would get all the auto instrumentation (including java.net.http.HttpClient) which requires the agent afaik, but also have the ability to slap `@WithSpan`  over the relevant methods.

**Comment by MikeGoldsmith** [comment]
Hey @vringar - When using the Java Agent to configure OpenTelemetry to get automatic instrumentation, the agent provides a configured TracerProvider to your app for it to use with manual instrumentation.

As @pkanal suggested above, you need to run your app using the agent then get a Tracer from the global tracer provider like this:
```java
final Tracer tracer = GlobalOpenTelemetry.getTracer("my-app");
```

As fas as I'm aware, the `@WithSpan` decorator should work with an agent configuration because it should use the registered TracerProvider. Have you had trouble with this?

This is a [simple Java Spring app](https://github.com/honeycombio/example-greeting-service/blob/main/java/message-service/src/main/java/io/honeycomb/examples/message/MessageService.java) that uses the agent, the @WithSpan decorator and creates a manual span - maybe that'll help guide you.
